image: alpine/latest
packages:
  - rsync
  - hugo
sources:
  - git@github.com:manu-cyber/c3stoc-website.git
secrets:
  - 8d08db0a-8b59-4026-a85e-90da7ab2342f
  - 2f4d6213-d8d0-41f6-ba8c-4572ac25bfac
tasks:
  - build: |
      cd c3stoc-website
      hugo
  - deploy: |
      cd c3stoc-website
      if [ "$(git rev-parse origin/main)" == "$(git rev-parse HEAD)" ] ; then
        sshopts="ssh -o StrictHostKeyChecking=no"
        rsync -e "$sshopts" -rP --del --force public/ irimi1@wirtanen.uberspace.de:/var/www/virtual/irimi1/stickeroperation.center/
       else
         echo "Not the 'main' branch, skipping deployment"
       fi
