image: alpine/latest
packages:
  - rsync
  - hugo
sources:
  - git@github.com:manu-cyber/c3stoc-website.git
secrets:
  - 2f764dcf-925b-44bf-b97e-e78039fedd15
tasks:
  - build: |
      cd c3stoc-website
      hugo
  - deploy: |
      cd c3stoc-website
      if [ "$(git rev-parse origin/main)" == "$(git rev-parse HEAD)" ] ; then
        sshopts="ssh -o StrictHostKeyChecking=no"
        rsync --rsh="$sshopts" -rP --del --force public irimi1@wirtanen.uberspace.de:/var/www/virtual/irimi1/stickeroperation.center/
       else
         echo "Not the 'main' branch, skipping deployment"
       fi
