name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch themes
          submodules: true
          fetch-depth: 0

      - name: Install hugo
        run: |
          sudo apt-get update
          sudo apt-get install hugo

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          hugo
